spring:
  application:
    name: payment-service
  config:
    import: "optional:aws-parameterstore:/payment-service/"
  data:
    mongodb:
      uri: ${MONGODB_URI}

mercadopago:
  token: ${MERCADO_PAGO_TOKEN}
  notification-url: ${MP_NOTIFICATION_URL}
  user-id: ${MP_USER_ID}

cloud:
  aws:
    sns:
      topic:
        arn: ${SNS_TOPIC_ARN}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always