apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: production
type: Opaque
stringData:
  MONGODB_URI: ${MONGODB_URI}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  MERCADO_PAGO_TOKEN: ${MERCADO_PAGO_TOKEN}
  SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
